version: "2"

services:
    keycloak1:
        container_name:                 mykeycloak1 
        build:                          .                   
        image:                          my-keycloak:1.0.0
        ports:
                                      - 8080:8080  
                                      - 8443:8443
        environment:
            KEYCLOAK_ADMIN:             admin
            KEYCLOAK_ADMIN_PASSWORD:    password
            KC_DB_URL:                  jdbc:postgresql://mydb:5432/keycloak
            KC_DB_USERNAME:             keycloak
            KC_DB_PASSWORD:             password
        command:                        start-dev           
    mydb:
        container_name:                 mipostgres
        image:                          postgres:15.2
        environment:
            POSTGRES_USER:              keycloak
            POSTGRES_PASSWORD:          password
        volumes:
                                      - /home/ubuntu/environment/data/postgresql:/var/lib/postgresql/data
    my-email-server:                    
        image:                          mailhog/mailhog
        container_name:                 mailhog
        ports:
                                      - 1025:1025   # smtp
                                      - 8081:8025
        