version: "2"

services:

    keycloak1:
        container_name:                 mykeycloak1 
        build:                          .                   
        image:                          my-keycloak:1.0.0
        ports:
                                      - 8080:8080  
                                      - 8443:8443
        environment:
            KEYCLOAK_ADMIN:             admin
            KEYCLOAK_ADMIN_PASSWORD:    password
            KC_DB_URL:                  jdbc:postgresql://mydb:5432/keycloak
            KC_DB_USERNAME:             keycloak
            KC_DB_PASSWORD:             password
        command:                        start-dev           
        
    mydb:
        container_name:                 mipostgres
        image:                          postgres:15.2
        environment:
            POSTGRES_USER:              keycloak
            POSTGRES_PASSWORD:          password
        volumes:
                                      - /home/ubuntu/environment/data/postgresql:/var/lib/postgresql/data
    my-email-server:                    
        image:                          mailhog/mailhog
        container_name:                 mailhog
        ports:
                                      - 1025:1025   # smtp
                                      - 8081:8025

    ldapserver:
        image: osixia/openldap:latest
        command: "--loglevel info"
        container_name: ldapserver
        hostname: ldapserver
        ports:
          - "389:389" #  ldap://
          - "636:636" #  ldaps://
        volumes:
          - /home/ubuntu/environment/data/openldap/ldap:/var/lib/ldap
          - /home/ubuntu/environment/data/openldap/slapd/config:/etc/ldap/slapd.d
          - /home/ubuntu/environment/data/openldap/certificates:/container/service/slapd/assets/certs
          - /home/ubuntu/environment/data/openldap/ldifs:/openldap/ldif  
        environment:
          - LDAP_ORGANISATION=training
          - LDAP_DOMAIN=training.local
          - LDAP_ADMIN_USERNAME=admin
          - LDAP_ADMIN_PASSWORD=password
          - LDAP_CONFIG_PASSWORD=password
          - "LDAP_BASE_DN=dc=training,dc=local"
          - LDAP_READONLY_USER=true
          - LDAP_READONLY_USER_USERNAME=user
          - LDAP_READONLY_USER_PASSWORD=password
          - LDAP_SEED_INTERNAL_LDIF_PATH=/openldap/ldif

    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        hostname: phpldapadmin
        ports:
          - "8084:80"
        environment:
          - PHPLDAPADMIN_LDAP_HOSTS=ldapserver
          - PHPLDAPADMIN_HTTPS=false
        depends_on:
          - ldapserver        